DELETE http://localhost:3003/api/blogs/5e9de926aee9b0246c20c2d4
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpaWthbGEiLCJpZCI6IjVlOWRlODBiYWVlOWIwMjQ2YzIwYzJkMCIsImlhdCI6MTU4NzQwNzQyMX0.ED-LhrhbDm4fuFtQuRB_hplNuxHztmiBkfb49bkhGiI